dictionaries = ["en_gb"]
words = [
    "backproc",
    "benchmarked",
    "benchmarking",
    "bmxx",
    "bourkestreetmall",
    "bsf",
    "chandola",
    "dampalgo",
    "dbscan",
    "delimitations",
    "deque",
    "examplepattern",
    "examplepoint",
    "gillis",
    "gungor",
    "ha ªapai",
    "humi",
    "hunga",
    "influxdata",
    "irf",
    "javaid",
    "kiruna",
    "knutstorp",
    "lai",
    "larus",
    "lasi",
    "lmas",
    "massv",
    "minimizing",
    "minkowski",
    "minkowski's",
    "mueen",
    "mueen's",
    "sdamp",
    "subsequence",
    "subsequence's",
    "subsequences",
    "tsl",
    "yeh",
    "yml",
    "zhong",
]
