dictionaries = ["en_gb"]
words = [
    "backproc",
    "benchmarked",
    "benchmarking",
    "bmxx",
    "bourkestreetmall",
    "bsf",
    "chandola",
    "dampalgo",
    "dbscan",
    "delimitations",
    "deque",
    "examplepattern",
    "examplepoint",
    "gillis",
    "gungor",
    "ha ªapai",
    "humi",
    "hunga",
    "influxdata",
    "irf",
    "javaid",
    "kiruna",
    "knutstorp",
    "lai",
    "larus",
    "lasi",
    "lmas",
    "massv",
    "minimizing",
    "minkowski",
    "minkowski's",
    "mueen",
    "mueen's",
    "rakthanmanon",
    "sdamp",
    "subsequence",
    "subsequence's",
    "subsequences",
    "tsl",
    "yeh",
    "yml",
    "zhong",
]

# Source: https://editorsmanual.com/articles/contractions-list/
# skipped some words around pronouns (we've, I'll etc.)
flag_words = [
    "don't",
    "didn't",
    "isn't",
    "wasn't",
    "aren't",
    "weren't",
    "hasn't",
    "haven't",
    "hadn't",
    "can't",
    "couldn't",
    "shouldn't",
    "won't",
    "wouldn't",
    "mustn't",
    "could've",
    "should've",
    "would've",
    "might've",
    "must've",
    "it's",
    "they're",
    "they've",
    "it'll",
    "they'll",
    "it'd",
    "they'd",
    "that's",
    "that'd",
    "who's",
    "who're",
    "who've",
    "who'd",
    "who'll",
    "what's",
    "what're",
    "what'll",
    "where's",
    "where'd",
    "when's",
    "why's",
    "why'd",
    "how's",
    "here's",
    "there's",
    "there'll",
    "there'd",
    "someone's",
    "somebody's",
    "nobody's",
    "something's",
    "nothing's",
    "let's",
]
