dictionaries = ["en_gb"]
words = [
    "benchmarked",
    "benchmarking",
    "dbscan",
    "delimitations",
    "gungor",
    "javaid",
    "lasi",
    "massv",
    "minimizing",
    "mueen",
    "mueen's",
    "subsequence",
    "subsequences",
    "yeh",
    "yml",
]
flag_words = []
ignore_paths = []
ignore_patterns = []
use_global = true
