dictionaries = ["en_gb"]
words = [
    "backproc",
    "benchmem",
    "bme",
    "bmesensor",
    "bmxx",
    "boniol",
    "bourke",
    "bsf",
    "chandola",
    "colbreak",
    "convolve",
    "creg",
    "dampalgo",
    "dampdata",
    "dbscan",
    "delimitations",
    "deque",
    "detectdiscords",
    "examplepattern",
    "examplepoint",
    "fft",
    "fieldinclude",
    "freebsd",
    "gillis",
    "goarch",
    "goos",
    "gungor",
    "hatwithrasp",
    "haʻapai",
    "humi",
    "hunga",
    "icm",
    "ifft",
    "influxd",
    "irf",
    "javaid",
    "jitter",
    "kiruna",
    "lai",
    "lan",
    "larus",
    "lasi",
    "lightsensor",
    "lmas",
    "ltr",
    "ltu",
    "luleå",
    "massv",
    "minkowski",
    "minkowski's",
    "movmean",
    "movstd",
    "mueen",
    "nextpower",
    "organization",
    "pagebreak",
    "pcpu",
    "percpu",
    "pmem",
    "rakthanmanon",
    "raspspecs",
    "scalable",
    "sdamp",
    "sensorhat",
    "sgp",
    "streamdamp",
    "subsequence",
    "subsequence's",
    "subsequences",
    "tagexclude",
    "totalcpu",
    "tsl",
    "ttb",
    "typst",
    "uptime",
    "voc",
    "waveshare",
    "yeh",
    "yeh's",
    "yml",
    "zhong",
    "zscore",
]

# Source: https://editorsmanual.com/articles/contractions-list/
# skipped some words around pronouns (we've, I'll etc.)
flag_words = [
    "don't",
    "didn't",
    "isn't",
    "wasn't",
    "aren't",
    "weren't",
    "hasn't",
    "haven't",
    "hadn't",
    "can't",
    "couldn't",
    "shouldn't",
    "won't",
    "wouldn't",
    "mustn't",
    "could've",
    "should've",
    "would've",
    "might've",
    "must've",
    "it's",
    "they're",
    "they've",
    "it'll",
    "they'll",
    "it'd",
    "they'd",
    "that's",
    "that'd",
    "who's",
    "who're",
    "who've",
    "who'd",
    "who'll",
    "what's",
    "what're",
    "what'll",
    "where's",
    "where'd",
    "when's",
    "why's",
    "why'd",
    "how's",
    "here's",
    "there's",
    "there'll",
    "there'd",
    "someone's",
    "somebody's",
    "nobody's",
    "something's",
    "nothing's",
    "let's",
]
